import type { Metadata } from "next";
import { Geist, Geist_Mono, Zalando_Sans_SemiExpanded } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const zalando = Zalando_Sans_SemiExpanded({
  variable: "--font-class-display",
  subsets: ["latin"],
  weight: "500",
  
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${zalando.variable} h-full antialiased`}
    >
      {/* <SmoothScroll /> */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
